import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { Navbar } from "../component/moleculs";

const Home: NextPage = () => {
  const [sideDrawerOpen, setDrawerOpen] = React.useState<boolean>(false);
  return (
    <div>
      <Head>
        <title>Wahyu Setiawan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
    </div>
  );
};

export default Home;
