name: PipelineNext

on:
  push:
    branches: [main]

jobs:
  lintTest:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          npm install

      - name: Run lint
        run: |
          echo "Running lint"
          npm run lint

      - name: Deploy to Production
        uses: actions/checkout@v2
        id: deploy-vercel-production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          scope: ${{ secrets.VERCEL_ORG_ID }}
